version: "3.9"

services:
  portfolio-manager:
    build: .
    image: portfolio-manager
    container_name: portfolio-manager-container
    ports:
      - "8080:8080"
    environment:
      STOCK_API_HOST: stock-prices-mock-api-container
      STOCK_API_PORT: 8080
    depends_on:
      mysql-database:
        condition: service_healthy
    networks:
      - portfolio-manager

  mysql-database:
    image: mysql/mysql-server
    container_name: mysql-container
    ports:
      - "1234:3306"
    environment:
      MYSQL_DATABASE: portfolio_manager
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
        - portfolio-manager-data:/var/lib/mysql
    networks:
      - portfolio-manager
    restart: unless-stopped

volumes:
  portfolio-manager-data:

networks:
  portfolio-manager:
    name: portfolio-manager-network
