version: "3.9"

services:
  portfolio-manager:
    build: .
    image: portfolio-manager
    container_name: portfolio-manager-container
    ports:
      - "8080:8080"
    environment:
      STOCK_API_HOST: stock-prices-mock-api-container
      STOCK_API_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: kafka-container:9092
    depends_on:
      mysql-database:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - portfolio-manager

  mysql-database:
    image: mysql/mysql-server
    container_name: mysql-container
    ports:
      - "1234:3306"
    environment:
      MYSQL_DATABASE: portfolio_manager
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
        - portfolio-manager-data:/var/lib/mysql
    networks:
      - portfolio-manager
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.8.2
    container_name: zookeeper-container
    ports:
      - "12181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - portfolio-manager-zookeeper-data:/bitnami
    networks:
      - portfolio-manager

  kafka:
    image: bitnami/kafka
    container_name: kafka-container
    ports:
      - "19092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-container:2181
    volumes:
      - portfolio-manager-kafka-data:/bitnami
    depends_on:
      - zookeeper
    healthcheck:
        test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
        interval: 5s
        timeout: 10s
        retries: 5
    networks:
      - portfolio-manager

volumes:
  portfolio-manager-data:
  portfolio-manager-zookeeper-data:
  portfolio-manager-kafka-data:

networks:
  portfolio-manager:
    name: portfolio-manager-network
